# .circleci/config.yml
version: 2.1
orbs:
  node: circleci/node@5
jobs:
  # First job declared is for building things...
  build:
    executor: node/default
    steps:
      - checkout
      - run: echo "Building things..."
      - run: echo "Install dependencies"
#      - node/install-packages:
#        pkg-manager: npm
      # Code analysing
      - run: echo "Running analysing and security"
#      - run: npm run lint
#      - run: npm audit --audit-level=moderate
      # Cleaning and packaging
      - run: echo "Running cleaning and packaging"
#      - run: npm run clean
#      - run: npm run build
  # Second job declared is for launching unit tests with Jest
  unit_tests:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      # Installing dependencies
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install jest-junit
      - run:
          name: Run tests
          command: npm run test:ci
      - store_test_results:
          path: ./test-results/
  # Deploy development environment
  deploy_dev:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to development environment..."
  # Deploy integration environment
  deploy_int:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to integration environment..."
  # Deploy production environment
  deploy_prod:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to production environment..."
  # Integration tests
  int_tests:
    executor: node/default
    steps:
      - checkout
      # Installing dependencies
      - node/install-packages:
          pkg-manager: npm
      - run: echo "Running integration tests..."
  #      - run: npm run test:integration
      - store_test_results:
          path: ./test-results/integration
  # Regression tests
  reg_tests:
    executor: node/default
    steps:
      - checkout
      # Installing dependencies
      - node/install-packages:
          pkg-manager: npm
      - run: echo "Running regression tests..."
  #      - run: npm run test:regression
      - store_test_results:
          path: ./test-results/regression
  # Performance tests
  perf_tests:
    executor: node/default
    steps:
      - checkout
      # Installing dependencies
      - node/install-packages:
          pkg-manager: npm
      - run: echo "Running performance tests..."
  #      - run: npm run test:performance
      - store_test_results:
          path: ./test-results/performance
  # Security tests
  secu_tests:
    executor: node/default
    steps:
      - checkout
      # Installing dependencies
      - node/install-packages:
          pkg-manager: npm
      - run: echo "Running security tests..."
  #      - run: npm audit --audit-level=moderate
      - store_test_results:
          path: ./test-results/security
  # Compatibility tests
  compatible_tests:
    executor: node/default
    steps:
      - checkout
      # Installing dependencies
      - node/install-packages:
          pkg-manager: npm
      - run: echo "Running compatibility tests..."
  #      - run: npm run test:compatibility
      - store_test_results:
          path: ./test-results/compatibility
  # Accessibility tests
  access_tests:
    executor: node/default
    steps:
      - checkout
      # Installing dependencies
      - node/install-packages:
          pkg-manager: npm
      - run: echo "Running accessibility tests..."
#      - run: npm run test:accessibility
      - store_test_results:
          path: ./test-results/accessibility
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - /^feature.*/
                - /^hotfix.*/
      - unit_tests:
          requires:
            - build
      - int_tests:
          requires:
            - unit_tests
      - reg_tests:
          requires:
            - int_tests
      - perf_tests:
          requires:
            - reg_tests
      - secu_tests:
          requires:
            - perf_tests
      - compatible_tests:
          requires:
            - secu_tests
      - access_tests:
          requires:
            - compatible_tests
      - deploy_dev:
          requires:
            - access_tests
          filters:
            branches:
              only:
                - develop
      - deploy_int:
          requires:
            - unit_tests
          filters:
            branches:
              only:
                - integration
      - deploy_prod:
          requires:
            - unit_tests
          filters:
            branches:
              only:
                - master
