# .circleci/config.yml
version: 2.1
orbs:
  node: circleci/node@5
jobs:
  # First job declared is for building things..
  build:
    executor: node/default
    steps:
      - checkout
      - run: echo "Building things..."
  # Second job declared is for launching unit tests with Jest
  unit_tests:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install jest-junit
      - run:
          name: Run tests
          command: npm run test:ci
      - store_test_results:
          path: ./test-results/
  # Deploy development environment
  deploy_dev:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to development environment..."
  # Deploy integration environment
  deploy_int:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to integration environment..."
  # Deploy production environment
  deploy_prod:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to production environment..."
  # Test feature and hotfix branches without deployment
  deploy_feat_hot:
    executor: node/default
    steps:
      - checkout
      - run: echo "Runnin tests on feature/hotfix branch..."
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - unit_tests:
          requires:
            - build
      - deploy_dev:
          requires:
            - unit_tests
          filters:
            branches:
              only:
                - develop
      - deploy_int:
          requires:
            - unit_tests
          filters:
            branches:
              only:
                - integration
      - deploy_prod:
          requires:
            - unit_tests
          filters:
            branches:
              only:
                - master
      - deploy_feat_hot:
          require:
            - unit_tests
          filters:
            branches:
              only:
              - /^feature.*/
              - /^hotfix.*/
